import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        StringBuilder ans = new StringBuilder("============= Order details =============\n");
        int totals = 0;

        // 计算优惠
        int cost01 = 0, cost02 = 0;
        List<String> stringList = this.salesPromotionRepository.findAll().get(1).getRelatedItems();

        // 优惠的项
        List<String> costList = new ArrayList<>();

        for (int i = 0; i < inputs.size(); i++) {
            String input = inputs.get(i);
            String id = input.substring(0, 8);
            String num = input.substring(input.indexOf(" x ") + 3);
            List<Item> itemList = this.itemRepository.findAll();

            // 找出编号的名字
            for (int j = 0; j < itemList.size(); j++) {
                if(id.equals(itemList.get(j).getId())) {
                    // 添加这一项
                    Item item = itemList.get(j);
                    Integer total = Integer.parseInt(num) * (int) item.getPrice();
                    totals += total;
                    ans.append(item.getName()).append(" x ").append(num).append(" = ").append(total.toString()).append(" yuan\n");

                    // 判断是否优惠
                    for (int z = 0; z < stringList.size(); z++) {
                        if(stringList.get(z).equals(item.getId())) {
                            cost02 += item.getPrice() / 2.0;
                            costList.add(item.getName());
                        }
                    }
                    break;
                }
            }
        }
        ans.append("-----------------------------------\n");
        cost01 = (totals / 30) * 6;

        int sum = 0;
        if(cost01 == 0 && cost02 == 0){
            ans.append("Total：").append(totals).append(" yuan\n").append("===================================");
            return ans.toString();
        }else if(cost01 >= cost02){
            ans.append("Promotion used:\n").append("满30减6 yuan，saving ").append(cost01);
            sum = totals - cost01;
        }else{
            ans.append("Promotion used:\n").append("Half price for certain dishes (");
            for (int i = 0; i < costList.size(); i++) {
                ans.append(costList.get(i));
                if(i == costList.size() - 1) {
                    ans.append(")，saving ");
                }else{
                    ans.append("，");
                }
            }
            ans.append(cost02);
            sum = totals - cost02;
        }
        ans.append(" yuan\n").append("-----------------------------------\n").append("Total：").append(sum).append(" yuan\n").append("===================================");
        System.out.println(ans.toString());
        return ans.toString();
    }
}
